### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by yqy6611** [AnantharamanLab/VIBRANT#100]
Hi, 

I encountered this error:

(vibrant) e2s2@e2s2-super-server-1:~/Softwares/VIBRANT$ python3 VIBRANT_run.py -h
Traceback (most recent call last):
  File "VIBRANT_run.py", line 24, in <module>
    import matplotlib
  File "/home/e2s2/miniconda3/envs/vibrant/lib/python3.7/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/home/e2s2/miniconda3/envs/vibrant/lib/python3.7/site-packages/matplotlib/rcsetup.py", line 28, in <module>
    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
  File "/home/e2s2/miniconda3/envs/vibrant/lib/python3.7/site-packages/matplotlib/fontconfig_pattern.py", line 15, in <module>
    from pyparsing import (Literal, ZeroOrMore, Optional, Regex, StringEnd,
  File "/home/e2s2/miniconda3/envs/vibrant/lib/python3.7/site-packages/pyparsing/__init__.py", line 129, in <module>
    from .util import *
  File "/home/e2s2/miniconda3/envs/vibrant/lib/python3.7/site-packages/pyparsing/util.py", line 14, in <module>
    class __config_flags:
  File "/home/e2s2/miniconda3/envs/vibrant/lib/python3.7/site-packages/pyparsing/util.py", line 17, in __config_flags
    _all_names: list[str] = []
TypeError: 'type' object is not subscriptable

Anyone knows how to solve it? Many thanks!

**Comment by KrisKieft** [comment]
I'm not sure what the issue is but my guess is there is a version issue. At the time of writing VIBRANT python >=3.5 and any matplotlib seemed to work. I'd suggest creating an environment with python v3.7 as an example and see if that works.

**Comment by yqy6611** [comment]
I've solved this problem myself by downgrading the pyparsing package to 2.4.7.
