### ISSUE TITLE
VIBRANT v1.2.1 draw a picture error

### ISSUE THREAD

**Issue by liuguoqi** [AnantharamanLab/VIBRANT#38]
Dear prof,
                 I'm interested  your software VIBRANT  . You have done much work !
                 I have installed VIBRANT v1.2.1 ,but run error?please help me ? 
'Rectangle' object has no property 'normed'
Traceback (most recent call last):
  File "/home/software/py3/envs/vs/bin/VIBRANT_run.py", line 790, in <module>
    figure = sns.distplot(length_list, bins=size, kde=False, rug=False, color='green')
  File "/home/software/py3/envs/vs/lib/python3.6/site-packages/seaborn/distributions.py", line 215, in distplot
    color=hist_color, **hist_kws)
  File "/home/software/py3/envs/vs/lib/python3.6/site-packages/matplotlib/__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/software/py3/envs/vs/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 6819, in hist
    p.update(kwargs)
  File "/home/software/py3/envs/vs/lib/python3.6/site-packages/matplotlib/artist.py", line 1006, in update
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/home/software/py3/envs/vs/lib/python3.6/site-packages/matplotlib/artist.py", line 1006, in <listcomp>
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/home/software/py3/envs/vs/lib/python3.6/site-packages/matplotlib/artist.py", line 1002, in _update_property
    .format(type(self).__name__, k))
               Numpy == 1.17.0
               Scikit-learn ==  0.21.3 
               Is it a version issue？ seaborn or matplotlib ? My seaborn == 0.7.1,matplotlib == 3.2.2

**Comment by KrisKieft** [comment]
Hi,

I ran a couple tests and it looks like the issue is seaborn. I could not replicate your exact error with seaborn v0.7.1 but I did get it with v0.8.1. I'm not sure what causes that. I would suggest updating using `pip install --upgrade seaborn==0.9.0`. This would be v0.9.0. If you have issues with this or do not want to do it, then you can use the flag for suppressing plot outputs. I hope that helps.

Kris

**Comment by liuguoqi** [comment]
seaborn==0.9.0 is ok , THX !
