### ISSUE TITLE
Not all files transferred during git clone, or bioconda install

### ISSUE THREAD

**Issue by reesea22** [AnantharamanLab/VIBRANT#54]
First, thank you for the very easy to follow installation instructions!

I am receiving the following errors when trying to run VIBRANT_setup.py after installing VIBRANT in a conda environment (bioconda and git clone also did not work for me).

python3 databases/VIBRANT_setup.py

This script will download, extract subsets and press HMM profiles for VIBRANT.
This process will require ~20GB of temporary free storage space, but the final size requirement is ~11GB in the form of pressed HMM databases.
Please be patient. This only needs to be run once and will take a few minutes.
Logger started. Check log file for messages and errors.
tar (child): profiles.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
gzip: Pfam-A.hmm.gz: No such file or directory
tar: Child returned status 2
tar: Error is not recoverable: exiting now
cat: profiles/K*.hmm: No such file or directory
rm: cannot remove ‘profiles’: No such file or directory

Error: Failed to open key file profile_names/VIBRANT_vog_profiles.txt

Error: File format problem in trying to open HMM file kegg_temp.HMM.
File exists, but appears to be empty?

mv: cannot stat ‘Pfam-A.hmm’: No such file or directory
rm: cannot remove ‘profiles.tar.gz’: No such file or directory

Error: File format problem in trying to open HMM file VOGDB94_phage.HMM.
File exists, but appears to be empty?

Error: File existence/permissions problem in trying to open HMM file KEGG_profiles_prokaryotes.HMM.
HMM file KEGG_profiles_prokaryotes.HMM not found (nor an .h3m binary of it)

Error: File existence/permissions problem in trying to open HMM file Pfam-A_v32.HMM.
HMM file Pfam-A_v32.HMM not found (nor an .h3m binary of it)

grep: VIBRANT-1.2.1/databases/KEGG_profiles_prokaryotes.HMM: No such file or directory
Traceback (most recent call last):
  File "databases/VIBRANT_setup.py", line 229, in <module>
    listing_shell = subprocess.check_output(listing, shell=True)
  File "/VIBRANT/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/VIBRANT/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'grep -c "NAME" /VIBRANT-1.2.1/databases/KEGG_profiles_prokaryotes.HMM' returned non-zero exit status 2

**Comment by KrisKieft** [comment]
Hi,

My first guess is that something appears to be wrong with `wget` of the HMM profiles. This error is harder to troubleshoot because I had a lot of `wget` outputs be hidden. Can you trying just typing `wget` on the command line and ensure you have it installed?

**Comment by pur80a** [comment]
I had some similar problem: have you tried doing it manually (issue #39)?
This worked for me. The `database` directory is stored in `$VIBRANT_DATA_PATH` which is for me under `/apps/vibrant/1.2.1/share/vibrant-1.2.1/db`. From within this `databases` directory following the instructions from #39 did the trick. I hope this helps anyone facing the same problem.

**Comment by rotoscan** [comment]
Hello,

I had the same issue.

I followed the thread on issue #39 but I got the same problem.
On step 5:
 hmmfetch -o VOGDB94_phage.HMM -f vog_temp.HMM profile_names/VIBRANT_vog_profiles.txt

It expects this file to exist, but it is not there...

Any help is appreciated, I would really like to use this tool! =)

Best,
Rodolfo

**Comment by pur80a** [comment]
@rotoscan if `VIBRANT_run.py` is in your `$PATH`, then this command should give you the location of `VIBRATN_vog_profiles.txt` if you've installed with `conda install -c bioconda vibrant==1.2.1`: 
`readlink -f $(dirname $(which VIBRANT_run.py ))/../share/vibrant-1.2.1/db/databases/profile_names/VIBRANT_vog_profiles.txt`
with the according version number of course

**Comment by rotoscan** [comment]
That worked!

thanks a lot @pur80a !

**Comment by decrevi** [comment]
I recently had this same issue. It is due to wget not downloading the files from the two FTP sites.
I ended up downloading the files manually (using Chrome) and putting the files in the databases folder. Then I commented out the lines to download the files (mainly for speed, since wget waits a LONG time for it to time out), and ran the VIBRANT_setup.py . That seems to have fixed the issue. It would be good to fix the wget issue though, maybe that is due to server upgrades or wget version?
