### ISSUE TITLE
Vibrant no working

### ISSUE THREAD

**Issue by priscillaisaac98** [AnantharamanLab/VIBRANT#76]
Encountered error and have tried it multiple times

Below is the error message;
Downloading VIBRANT databases to /home/priscilla/anaconda3/envs/vibrant/share/vibrant-1.0.1...

This script will download, extract subsets and press HMM profiles for VIBRANT.
This process will require 20GB of temporary free storage space, but the final size requirement is ~11.2GB in the form of pressed HMM databases.
Please be patient. This only needs to be run once and will take a few minutes.

Verifying Pfam, KEGG and VOG source websites are available for download ...

Downloading HMM profiles for Pfam, KEGG and VOG from their source websites ...
2022-12-20 17:05:55 (350 KB/s) - Data connection: Connection timed out; Data transfer aborted.
2022-12-20 17:20:31 (166 KB/s) - Data connection: Connection timed out; Data transfer aborted.
Aborted (core dumped)
2022-12-20 17:52:16 (121 KB/s) - Data connection: Connection timed out; Data transfer aborted.
2022-12-20 18:07:31 URL:https://fileshare.csb.univie.ac.at/vog/vog94/vog.hmm.tar.gz [329720997/329720997] -> "vog.hmm.tar.gz" [3]
2022-12-20 18:25:21 (16.8 KB/s) - Data connection: Connection timed out; Data transfer aborted.
2022-12-20 18:44:57 (23.4 KB/s) - Data connection: Connection timed out; Data transfer aborted.
2022-12-20 19:04:45 (41.0 KB/s) - Data connection: Connection timed out; Data transfer aborted.
2022-12-20 19:26:27 (35.0 KB/s) - Data connection: Connection timed out; Data transfer aborted.
2022-12-20 19:46:03 (36.0 KB/s) - Data connection: Connection timed out; Data transfer aborted.
Error in server response, closing control connection.
2022-12-20 20:14:53 (33.2 KB/s) - Data connection: Connection timed out; Data transfer aborted.
Aborted (core dumped)

Unzipping profiles ...

gzip: Pfam-A.hmm.gz: unexpected end of file

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

Concatenating individual profiles ...

Extracting profiles used for VIBRANT ...

Error: File existence/permissions problem in trying to open HMM file Pfam-A.hmm.
HMM file Pfam-A.hmm not found (nor an .h3m binary of it)

Error: File existence/permissions problem in trying to open HMM file Pfam-A.hmm.
HMM file Pfam-A.hmm not found (nor an .h3m binary of it)

Error: bad file format in HMM file kegg_temp.HMM

Retrieved 19182 HMMs.
mv: cannot stat 'Pfam-A.hmm': No such file or directory

Pressing profiles used for VIBRANT ...

Error: Working...    File existence/permissions problem in trying to open HMM file Pfam-A_plasmid_v32.HMM.
HMM file Pfam-A_plasmid_v32.HMM not found (nor an .h3m binary of it)

Working...    
Error: File existence/permissions problem in trying to open HMM file Pfam-A_phage_v32.HMM.
HMM file Pfam-A_phage_v32.HMM not found (nor an .h3m binary of it)

Error: File existence/permissions problem in trying to open HMM file Pfam-A_v32.HMM.
HMM file Pfam-A_v32.HMM not found (nor an .h3m binary of it)

done.
Pressed and indexed 3048 HMMs (3048 names).
Models pressed into binary file:   KEGG_profiles_prokaryotes.HMM.h3m
SSI index for binary model file:   KEGG_profiles_prokaryotes.HMM.h3i
Profiles (MSV part) pressed into:  KEGG_profiles_prokaryotes.HMM.h3f
Profiles (remainder) pressed into: KEGG_profiles_prokaryotes.HMM.h3p
done.
Pressed and indexed 19182 HMMs (19182 names).
Models pressed into binary file:   VOGDB94_phage.HMM.h3m
SSI index for binary model file:   VOGDB94_phage.HMM.h3i
Profiles (MSV part) pressed into:  VOGDB94_phage.HMM.h3f
Profiles (remainder) pressed into: VOGDB94_phage.HMM.h3p

Done. Several new databases are now in this folder.

VIBRANT should be ready to go. You can verify this by running VIBRANT_test_setup.py within this folder (databases/)

Testing VIBRANT databases...
grep: /home/priscilla/anaconda3/envs/vibrant/share/vibrant-1.0.1/databases/Pfam-A_phage_v32.HMM: No such file or directory
Traceback (most recent call last):
  File "/home/priscilla/anaconda3/envs/vibrant/share/vibrant-1.0.1/databases/VIBRANT_test_setup.py", line 49, in <module>
    listing_shell = subprocess.check_output(listing, shell=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/priscilla/anaconda3/envs/vibrant/lib/python3.11/subprocess.py", line 465, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/priscilla/anaconda3/envs/vibrant/lib/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'grep -c "NAME" /home/priscilla/anaconda3/envs/vibrant/share/vibrant-1.0.1/databases/Pfam-A_phage_v32.HMM' returned non-zero exit status 2.
VIBRANT databases are downloaded successfully.

**Comment by KrisKieft** [comment]
Hi,

There's a couple things here. First, it looks like you're installing v1.0.1. I HIGHLY discourage you to use an old version. Please use or specify the newest version. Second, it looks like the installation kept going despite not connecting to the Pfam website. Near the top you can see "Data connection: Connection timed out; Data transfer aborted." KEGG seems to have had an issue as well. Did you try simply repeating it? Try that out with v1.2.1.
