### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by Peng2555** [AnantharamanLab/VIBRANT#91]
When I was running run. py for VIBRANT, I encountered ImportError: cannot import name 'DtypeObj'. How should this problem be solved? And using pip to download 'DtypeObj' did not find the corresponding import. Help

**Comment by KrisKieft** [comment]
VIBRANT does not have any import called 'DtypeObj'. Can you please send the full error message?

**Comment by Peng2555** [comment]
This is all the error messages: Traceback (most recent call last):
  File "./VIBRANT_run.py", line 23, in <module>
    import pandas as pd
  File "/home/data/pp2/.conda/envs/VIBRANT/lib/python3.6/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/home/data/pp2/.conda/envs/VIBRANT/lib/python3.6/site-packages/pandas/core/api.py", line 5, in <module>
    from pandas.core.arrays.integer import (
  File "/home/data/pp2/.conda/envs/VIBRANT/lib/python3.6/site-packages/pandas/core/arrays/__init__.py", line 13, in <module>
    from .sparse import SparseArray  # noqa: F401
  File "/home/data/pp2/.conda/envs/VIBRANT/lib/python3.6/site-packages/pandas/core/arrays/sparse/__init__.py", line 3, in <module>
    from pandas.core.arrays.sparse.accessor import SparseAccessor, SparseFrameAccessor
  File "/home/data/pp2/.conda/envs/VIBRANT/lib/python3.6/site-packages/pandas/core/arrays/sparse/accessor.py", line 10, in <module>
    from pandas.core.arrays.sparse.array import SparseArray
  File "/home/data/pp2/.conda/envs/VIBRANT/lib/python3.6/site-packages/pandas/core/arrays/sparse/array.py", line 44, in <module>
    from pandas.core.arrays.sparse.dtype import SparseDtype
  File "/home/data/pp2/.conda/envs/VIBRANT/lib/python3.6/site-packages/pandas/core/arrays/sparse/dtype.py", line 9, in <module>
    from pandas._typing import Dtype, DtypeObj
ImportError: cannot import name 'DtypeObj'

**Comment by Peng2555** [comment]
Like this:VIBRANT Error: Please install VIBRANT dependancy module(s). See below for the encountered error:

cannot import name 'DtypeObj'

**Comment by KrisKieft** [comment]
The import error comes from pandas. What version of pandas do you have?

**Comment by Peng2555** [comment]
pandas==1.1.5

**Comment by KrisKieft** [comment]
Try updating pandas
